# -- Inspired by Catppuccin (https://github.com/catppuccin/tmux#recommended-default-configuration)

# -- General
 
# Setting the prefix from C-b to C-a
unbind C-b
set -g prefix C-a

set -g base-index 1 # Begin at 1 for windows
setw -g pane-base-index 1
set -g renumber-windows on # renumber windows sequentially after closing any of them

set -g mouse on

setw -g mode-keys vi # enable vi keys.
bind-key -T copy-mode-vi v send-keys -X begin-selection # Setup 'v' to begin selection as in Vim


# -- Status line
set -g status-left ""
set -g window-status-format " #I: #{?#{!=:#W,fish},#W,#T} "
# set -g window-status-current-format " #I: #{?#{!=:#W,fish},#W,#T} "
set -g window-status-separator " "

# Catppuccin Macchiato
# set -g status-style "bg=#282C34 fg=white"
# set -g window-status-style "fg=white bg=#282C34"
# set -g window-status-current-style "fg=#11111b bg=#CBA6F7"
# set -g status-right "#[fg=black,bg=#CBA6F7] 󰃰 %Y-%m-%d %H:%M "

# rose-pine-dawn
set -g status-style "bg=#FFFAF3 fg=#797593"
set -g window-status-current-style "fg=#d7827f bg=#fae8e1"
set -g status-right "#[fg=#d7827f bg=#fae8e1] 󰃰 %Y-%m-%d %H:%M "


# -- Navigation
# How to determine if we're at the end of the list of panes in Helix and should switch to a Tmux pane?
# is_hx='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|hx)(diff)?\$"'
# bind -n C-h if-shell "$is_hx" "send-keys C-w h" "select-pane -L"
# bind -n C-j if-shell "$is_hx" "send-keys C-w j" "select-pane -D"
# bind -n C-k if-shell "$is_hx" "send-keys C-w k" "select-pane -U"
# bind -n C-l if-shell "$is_hx" "send-keys C-w l" "select-pane -R"
bind -n "C-h" "select-pane -L"
bind -n "C-j" "select-pane -D"
bind -n "C-k" "select-pane -U"
bind -n "C-l" "select-pane -R"

bind "\\" "split-window -h -c \"#{pane_current_path}\""
bind "-" "split-window -v -c \"#{pane_current_path}\""


# -- Use Fish as shell
set-option -g default-command "reattach-to-user-namespace -l /opt/homebrew/bin/fish"
set-option -g default-command /opt/homebrew/bin/fish
set-option -g default-shell /opt/homebrew/bin/fish
