#!/usr/bin/env ruby

# Read this blog to know more about this script.
# http://blog.bigbinary.com/2013/09/19/do-not-allow-force-pusht-to-master.html

class PrePushHandler
  PROTECTED_BRANCHES =  ['master', 'main', 'dev', 'staging']

  def handle
    reject if pushing_to_integration_branch? && forced_push?
  end

  private

  def pushing_to_integration_branch? =  PROTECTED_BRANCHES.include?(current_branch)
  def current_branch = %x{git branch --show-current}.strip
  def forced_push? = %x{ps -ocommand= -p #{Process.ppid}}.match(/--force|-f/)

  def reject
    messages =[
      "Your attempt to force push to the integration branch has been rejected.",
      "If you still want to force push, ignore the pre_push git hook by adding --no-verify.",
    ]

    puts "*"*40
    messages.flatten.each { puts _1 }
    puts "*"*40

    exit 1
  end
end

PrePushHandler.new.handle
