-- " :iab entry 2021/04/01 Transaction<CR>  Account    $0.00<CR>
-- :iab rbcop # rubocop:disable Metrics/LineLength
-- :iab pry require 'pry'; binding.pry
-- " # NOTE: (`strftime("%Y-%m-%d")`) `system("whoami | tr -d '\n'")` => ${1}
-- :iab note # NOTE: (YYYY-mm-dd) Noah Settersten =>
