[general]
working_directory = "/Users/noah"
import = ["/Users/noah/.config/alacritty/catppuccin-macchiato.toml"]

# Font options
[font]
size = 14.0

[font.normal]
family = "Mononoki Nerd Font"

[font.offset]
x = 0
y = 1

# family = "Iosevka" # font size 13.0, offset 0
# family = "Iosevka Nerd Font" # Use with font size 14.0, offset.x 1, offset.y -2
# family = "Iosevka Nerd Font Propo" # Use with font size 13.0, offset.x 1
# family = "Monaco NERD Font" # Use with font size 12.0, offset.y 1
# family = "Mononoki Nerd Font Mono" # Use with font size 14.0, offset.y 1
# family = "FantasqueSansM Nerd Font Mono" # Use with font size 14.0
# family = "EnvyCodeR Nerd Font Mono" # Use with font size 14.0, offset.y -1

[window]
decorations = "buttonless"
opacity = 0.95

[terminal.shell]
program = "/opt/homebrew/bin/fish"
