import = ["/Users/noah/.config/alacritty/catppuccin-macchiato.toml"]
working_directory = "/Users/noah"

[font]
size = 13.0

[font.normal]
    # family: Monaco NERD Font # Use with font size 12.0
    # family: Mononoki Nerd Font Mono # Use with font size 13.0
    # family: FantasqueSansM Nerd Font Mono # Use with font size 14.0
    # family: EnvyCodeR Nerd Font Mono # Use with font size 14.0, offset.y -1
family = "Iosevka"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
decorations = "buttonless"
opacity = 0.95
