# -- Helix configuration --
theme = "catppuccin_macchiato" # Others: "kanagawa", "rose_pine", "rose_pine_moon", everforest_dark 
  
[editor]
color-modes = true
auto-format = true
cursorline = true
rulers = [100]
bufferline = "multiple"
true-color = true
end-of-line-diagnostics = "hint"
default-yank-register = "+" # https://jvns.ca/blog/2025/10/10/notes-on-switching-to-helix-from-vim/#my-configuration

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]


# -- Mappings --
[keys.normal]
Y = ["extend_to_line_end", "yank"]
D = ["extend_to_line_end", "delete_selection"]

## From https://dev.to/rajasegar/helix-tmux-and-lazygit-7nj#update and https://github.com/helix-editor/helix/discussions/12045
C-g = [":write-all", ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80%% -h80%% -E lazygit", ":redraw", ":reload-all"]

## From https://github.com/helix-editor/helix/issues/3035#issuecomment-2715731119
C-b = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name} | cut -d' ' -f1-4 | sed 's/$/)/g'}"

## From https://tqwewe.com/blog/enhanced-helix-config/
X = "select_line_above"

[keys.select]
X = "select_line_above"


# -- My custom tooling --
[keys.normal.t] # Testing
## Try https://github.com/helix-editor/helix/discussions/14227
T = ":sh tmux send-keys -t{last} \"bin/rails test %{buffer_name}\" Enter"

[keys.normal.space.z] # Holds personal mappings
i = ":toggle file-picker.git-ignore"
# r =  ":reload-all"
