-- let g:tmux_navigator_save_on_switch = 1

-- " This switches the cursor into a pipe when in insert mode tmux will only
-- " forward escape sequences to the terminal if surrounded by a DCS sequence
-- " http://sourceforge.net/mailarchive/forum.php?thread_name=AANLkTinkbdoZ8eNR1X2UobLTeww1jFrvfJxTMfKSq-L%2B%40mail.gmail.com&forum_name=tmux-users
-- if has('nvim')
  -- " let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
-- else
  -- if exists('$TMUX')
    -- let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    -- let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
  -- else
    -- let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    -- let &t_EI = "\<Esc>]50;CursorShape=0\x7"
  -- endif
-- endif
