-- let g:buffergator_viewport_split_policy="B"
-- let g:buffergator_split_size=10
-- let g:buffergator_suppress_keymaps=1
-- let g:buffergator_sort_regime = "mru"
-- map <Leader>b :BuffergatorToggle<cr>
