-- set diffopt+=vertical
-- nnoremap <leader>gd :Gdiff<cr>
-- nnoremap <leader>gst :Git<cr>
-- nnoremap <leader>gw :Gwrite<cr>
-- nnoremap <leader>ge :Gedit<cr>
-- nnoremap <leader>gb :Git blame -w -M<cr>
-- nnoremap <leader>gB :Gitv!<cr>
-- nnoremap <leader>gco :Gread<cr>
-- nnoremap <leader>gcm :Gcommit<cr>
-- nnoremap <leader>glg :0Glog<cr>
-- nnoremap <leader>gl :Git log --oneline<cr>
